### PR TITLE
Add POW for sFUEL, update community pool logic

### PR DESCRIPTION
**Pull request by payvint**
Adding support of executing POW tx from random wallet to faucet

If faucet.json is present in `src/` folder

pow library provided by @TheGreatAxios

### CODE REVIEW

**Comment by dmytrotkk** [comment]
still WIP - community pool component logic has to be altered

**Comment by TheGreatAxios** [comment]
Yes, pulling down the most recent code now.

**Comment by dmytrotkk** [comment]
scheduled to 1.1.0 release

**Comment by dmytrotkk** [comment]
UPD: closing this PR, will re-open to develop branch https://github.com/skalenetwork/bridge-ui/pull/31

**Pull request closed without merging**
